project:
  type: book

book:
  title: "LATIS R Quarto Workshop"
  author: "Norah Jones"
  date: "2/22/2024"
  chapters:
    - index.qmd
    - intro.qmd
    - Results.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  pdf:
    documentclass: scrreprt



