project:
  type: book

execute: 
  echo: false
  warning: false
  message: false

book:
  title: "LATIS R Quarto Workshop"
  #author: "Norah Jones"
  author:
    - name: "Norah Jones"
      email: "norajones@yesthatsher.net"
      affiliation: 
        - name: "University of Minnesota"
          address: "1234 Main St, Minneapolis, MN 55455"
      orcid: "0000-0002-1825-0097"
  date: "3/28/2024"
  chapters:
    - index.qmd
    #- intro.qmd
    - Results.qmd
    - summary.qmd
    - discussion.qmd
    - references.qmd

bibliography: references.bib

format:
  pdf:
    documentclass: scrreprt
    # https://quarto.org/docs/journals/templates.html
    margin-left: "1.5in"
    margin-right: "1in"
    margin-top: "1in"
    margin-bottom: "1.5in"
    linestretch: 1.5
    template-partials:
      - templates/before-body.tex
      - templates/_dynamic_titlepage.tex
      - templates/copyright.tex
    include-before-body:
      - file: "templates/acknowledgement.tex"
      - file: "templates/dedication.tex"
      - file: "templates/abstract.tex"
    toc: true
    toc-depth: 2
    lof: true
    lot: true
    fontfamily: times
  html: 
    theme: cosmo
  docx:
    toc: true


