project:
  type: book

execute: 
  echo: false
  warning: false
  message: false

book:
  title: "LATIS R Quarto Workshop"
  author: "Norah Jones"
  date: "2/22/2024"
  chapters:
    - index.qmd
    - intro.qmd
    - results.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  pdf:
    documentclass: scrreprt
  html: 
    theme: cosmo
  docx:
    toc: true


