project:
  type: book

execute: 
  echo: false
  warning: false
  message: false

book:
  title: "LATIS R Quarto Workshop"
  #author: "Norah Jones"
  author:
    - name: "Norah Jones"
      email: "norajones@yesthatsher.net"
      affiliation: 
        - name: "University of Minnesota"
          address: "1234 Main St, Minneapolis, MN 55455"
      orcid: "0000-0002-1825-0097"
      metadata:
        advisor: "Dr. Joan Smith"
  date: "2/22/2024"
  chapters:
    - index.qmd
    - intro.qmd
    - Results.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  pdf:
    documentclass: scrreprt
    # https://quarto.org/docs/journals/templates.html
    template-partials:
      - templates/before-body.tex
      - templates/_dynamic_titlepage.tex
      - templates/_static_titlepage.tex
      - templates/copyright.tex
      - templates/acknowledgement.tex
      - templates/dedication.tex
      - templates/abstract.tex

    #include-before-body: 
    #  - file: "templates/copyright.tex"
    #  - file: "templates/acknowledgements.tex"
    #  - file: "templates/dedication.tex"
    #  - file: "templates/abstract.tex"
  html: 
    theme: cosmo
  docx:
    toc: true


